version: '3'
services:
  postgres:
    image: postgres:12.3
    container_name: contacts_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=contacts_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
